### ISSUE TITLE
1.1.8 regression: readable called an extra time at end of stream

### ISSUE THREAD

**Issue by jefftmills** [wdavidw/node-csv-parse#123]
I'm using the streaming API with a handler for the "readable" event which calls the "read" function. Starting with version 1.1.8, reading a file having one header line and one data line, "readable" is called 3 times:

1. The first time, calling read() returns an object representing the first data row with column values correctly mapped to the column headers as name:value in the object.
1. The second time, calling read() returns an object having a single property with the name being the first column header and the value being an empty string.
1. The third time, calling read() returns null, indicating there is no more data.

The 1st and 3rd of these are expected, the 2nd is the erroneous new behavior.
Reverting back to version 1.1.7 fixes this.

**Comment by wdavidw** [comment]
could you provide me with a small example to make sure i got it right ?

**Comment by jefftmills** [comment]
The attached zip file has a sample CSV file with 1 header row and 1 data row, and a stripped-down version of our code (I removed dependencies on the rest of our code and the logic to upload the records to Salesforce). Using this, I was able to re-create the problem with 1.1.9 but not 1.1.7.

[csv-parse-test.zip](https://github.com/wdavidw/node-csv-parse/files/708972/csv-parse-test.zip)

**Comment by tebs1200** [comment]
I'm getting a similar issue but I'm not using the streaming API. I have a file with a header row and 5 data rows. Since version 1.1.8, an additional empty record is being added at the end.

I've created a [simple project](https://github.com/tebs1200/csv-parse-example) that recreates the issue.

If you switch the csv-parse version to 1.1.7, the issue isn't present.

**Comment by wdavidw** [comment]
Latest release should fix the issue, please confirm

**Comment by tebs1200** [comment]
It's working as expected for me in 1.1.10

**Comment by jefftmills** [comment]
Sorry, it's still broken for me (both my "real" code and the test file I attached to this issue).

**Comment by wdavidw** [comment]
ok, I have reverted to 1.1.8 before a pull request broke rowDelimiter and re-implemented myself all code functionnalities since then. your code is not working.

**Comment by wdavidw** [comment]
thanks for your time

**Comment by jefftmills** [comment]
You wrote "your code is **not** working." Is that a typo and you meant "now working" or did you mean there is a problem with the sample code I attached?

**Comment by wdavidw** [comment]
sorry, *now* working

**Comment by jefftmills** [comment]
Tested version 1.2.0 with our full app and confirmed this problem is fixed. Thanks.
